name: thread
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
    sdk: ">=3.1.0 <4.0.0"

dependencies:
    flutter:
        sdk: flutter

    cupertino_icons: ^1.0.2
    go_router: ^10.1.0
    google_fonts: ^5.1.0
    font_awesome_flutter: ^10.5.0
    flutter_riverpod: ^2.3.7

    flutter_localizations:
        sdk: flutter
    intl: any
    flutter_svg: ^2.0.7

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^2.0.0

flutter:
    generate: true
    uses-material-design: true

    assets:
        - assets/

flutter_intl:
    enabled: true
