name: thread
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
    sdk: ">=3.1.0 <4.0.0"

dependencies:
    flutter:
        sdk: flutter

    cupertino_icons: ^1.0.2
    go_router: ^10.1.0
    google_fonts: ^4.0.4
    font_awesome_flutter: ^10.5.0
    flutter_riverpod: ^2.3.7
    permission_handler: ^10.4.5
    image_picker: ^1.0.4
    camera: ^0.10.5+4
    flutter_localizations:
        sdk: flutter
    intl: any
    flutter_svg: ^2.0.7
    gallery_saver: ^2.3.2

    video_player: ^2.5.1
dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^2.0.0

flutter:
    generate: true
    uses-material-design: true

    assets:
        - assets/
        - assets/icons/
        - assets/avatars/

flutter_intl:
    enabled: true
