// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR0bcU6JRqJyHxGFVEGKYW_FyXdnvC7nA',
    appId: '1:821699920655:web:d11665e7aafbfc89d5b47a',
    messagingSenderId: '821699920655',
    projectId: 'thread-clone-dd1f8',
    authDomain: 'thread-clone-dd1f8.firebaseapp.com',
    storageBucket: 'thread-clone-dd1f8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPsl7jgpDEyFUIQJupcOnMyrLOAyhyZq4',
    appId: '1:821699920655:android:42ab5ce1dbd973fed5b47a',
    messagingSenderId: '821699920655',
    projectId: 'thread-clone-dd1f8',
    storageBucket: 'thread-clone-dd1f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcXYY33NYtJllPkGYGEIrVIa1Ra1qxi9g',
    appId: '1:821699920655:ios:e4c4ed87b3d0d68ed5b47a',
    messagingSenderId: '821699920655',
    projectId: 'thread-clone-dd1f8',
    storageBucket: 'thread-clone-dd1f8.appspot.com',
    iosBundleId: 'com.example.thread',
  );
}
