import 'package:thread/main/model/list_data.dart';

final fakeData = [
  ListData(
    avatar: "assets/avatars/elon.webp",
    name: "Elon Musk",
    blueCheck: true,
    time: "4d",
    text: "Let's fight with Jujitsu, Mark. Are you scared?",
    images: ["assets/letsfight.png"],
    replies: 2,
    replyAvatars: ["assets/avatars/kimj.jpeg", "assets/avatars/johnwick.jpeg"],
    likes: 23284,
  ),
  ListData(
    avatar: "assets/avatars/zcbg.jpeg",
    name: "Mark Zuckerberg",
    blueCheck: true,
    time: "4d",
    text:
        "You are already dead. Do not be surprised by my brilliant technique.",
    images: ["assets/mark1.jpg"],
    replies: 0,
    replyAvatars: [],
    likes: 7321,
  ),
  ListData(
    avatar: "assets/avatars/nike.png",
    name: "Nike",
    blueCheck: true,
    time: "3d",
    text: "Need sponsorship? Just do it.",
    images: [],
    replies: 0,
    replyAvatars: [],
    likes: 211,
  ),
  ListData(
    avatar: "assets/avatars/johnwick.jpeg",
    name: "John Wick",
    blueCheck: true,
    time: "1d",
    text: "Nobody but me should talk about Jiu-Jitsu.",
    images: [],
    replies: 35,
    replyAvatars: [
      "assets/avatars/kimj.jpeg",
      "assets/avatars/ma.jpeg",
      "assets/avatars/tony.jpeg"
    ],
    likes: 211,
  ),
  ListData(
    avatar: "assets/avatars/kimj.jpeg",
    name: "Kim Jeong Un",
    blueCheck: false,
    time: "22h",
    text: "Do we also need to have a match, brother?",
    images: ["assets/kimj.jpeg"],
    replies: 2,
    replyAvatars: ["assets/avatars/ma.jpeg", "assets/avatars/trump.jpeg"],
    likes: 88971,
  ),
  ListData(
    avatar: "assets/avatars/fu.jpg",
    name: "FuBao",
    blueCheck: true,
    time: "17h",
    text: "나 푸바온데 당근 좀 주라",
    images: ["assets/fubao1.jpg"],
    replies: 0,
    replyAvatars: [],
    likes: 132,
  ),
  ListData(
    avatar: "assets/avatars/ma.jpeg",
    name: "Don Lee",
    blueCheck: true,
    time: "12h",
    text: "차 빼 이 새끼야",
    images: [
      "assets/ma1.jpg",
      "assets/ma2.jpeg",
      "assets/ma3.jpeg",
      "assets/ma4.jpeg"
    ],
    replies: 366,
    replyAvatars: [
      "assets/avatars/trump.jpeg",
      "assets/avatars/elon.webp",
      "assets/avatars/brucelee.jpeg"
    ],
    likes: 132,
  ),
  ListData(
    avatar: "assets/avatars/kimr.png",
    name: "Sunflower",
    blueCheck: false,
    time: "4h",
    text: "그렇게, 다 가져가야만 속이 시원했냐아",
    images: ["assets/batman.jpeg"],
    replies: 0,
    replyAvatars: [],
    likes: 1,
  ),
  ListData(
    avatar: "assets/avatars/mnk.jpg",
    name: "맑눈광",
    blueCheck: false,
    time: "22m",
    text: "ㅋㅋㅋ",
    images: [],
    replies: 0,
    replyAvatars: [],
    likes: 5,
  ),
];
