import 'package:thread/main/model/activity_data.dart';
import 'package:thread/main/model/list_data.dart';
import 'package:thread/main/model/search_data.dart';

final fakeData = [
  ListData(
    avatar: "assets/avatars/elon.webp",
    name: "Elon Musk",
    blueCheck: true,
    time: "4d",
    text: "Let's fight with Jujitsu, Mark. Are you scared?",
    images: ["assets/letsfight.png"],
    replies: 2,
    replyAvatars: ["assets/avatars/kimj.jpeg", "assets/avatars/johnwick.jpeg"],
    likes: 23284,
  ),
  ListData(
    avatar: "assets/avatars/zcbg.jpeg",
    name: "Mark Zuckerberg",
    blueCheck: true,
    time: "4d",
    text:
        "You are already dead. Do not be surprised by my brilliant technique.",
    images: ["assets/mark1.jpg"],
    replies: 0,
    replyAvatars: [],
    likes: 7321,
  ),
  ListData(
    avatar: "assets/avatars/nike.png",
    name: "Nike",
    blueCheck: true,
    time: "3d",
    text: "Need sponsorship? Just do it.",
    images: [],
    replies: 0,
    replyAvatars: [],
    likes: 211,
  ),
  ListData(
    avatar: "assets/avatars/johnwick.jpeg",
    name: "John Wick",
    blueCheck: true,
    time: "1d",
    text: "Nobody but me should talk about Jiu-Jitsu.",
    images: [],
    replies: 35,
    replyAvatars: [
      "assets/avatars/kimj.jpeg",
      "assets/avatars/ma.jpeg",
      "assets/avatars/tony.jpeg"
    ],
    likes: 211,
  ),
  ListData(
    avatar: "assets/avatars/kimj.jpeg",
    name: "Kim Jeong Un",
    blueCheck: false,
    time: "22h",
    text: "Do we also need to have a match, brother?",
    images: ["assets/kimj.jpeg"],
    replies: 2,
    replyAvatars: ["assets/avatars/ma.jpeg", "assets/avatars/trump.jpeg"],
    likes: 88971,
  ),
  ListData(
    avatar: "assets/avatars/fu.jpg",
    name: "FuBao",
    blueCheck: true,
    time: "17h",
    text: "나 푸바온데 당근 좀 주라",
    images: ["assets/fubao1.jpg"],
    replies: 0,
    replyAvatars: [],
    likes: 132,
  ),
  ListData(
    avatar: "assets/avatars/ma.jpeg",
    name: "Don Lee",
    blueCheck: true,
    time: "12h",
    text: "차 빼 이 새끼야",
    images: [
      "assets/ma1.jpg",
      "assets/ma2.jpeg",
      "assets/ma3.jpeg",
      "assets/ma4.jpeg"
    ],
    replies: 366,
    replyAvatars: [
      "assets/avatars/trump.jpeg",
      "assets/avatars/elon.webp",
      "assets/avatars/brucelee.jpeg"
    ],
    likes: 132,
  ),
  ListData(
    avatar: "assets/avatars/kimr.png",
    name: "Sunflower",
    blueCheck: false,
    time: "4h",
    text: "그렇게, 다 가져가야만 속이 시원했냐아",
    images: ["assets/batman.jpeg"],
    replies: 0,
    replyAvatars: [],
    likes: 1,
  ),
  ListData(
    avatar: "assets/avatars/mnk.jpg",
    name: "맑눈광",
    blueCheck: false,
    time: "22m",
    text: "ㅋㅋㅋ",
    images: [],
    replies: 0,
    replyAvatars: [],
    likes: 5,
  ),
];

final fakeDataSearch = [
  SearchData(
    avatar: "assets/avatars/elon.webp",
    name: "Elon Musk",
    account: "elonmusk",
    blueCheck: true,
    followers: "11.5M",
  ),
  SearchData(
    avatar: "assets/avatars/brucelee.jpeg",
    name: "Bruce Lee",
    account: "iambruce",
    blueCheck: true,
    followers: "38.2M",
  ),
  SearchData(
    avatar: "assets/avatars/johnwick.jpeg",
    name: "John Wick",
    account: "johnwickofficial",
    blueCheck: true,
    followers: "5.3M",
  ),
  SearchData(
    avatar: "assets/avatars/kimj.jpeg",
    name: "Kim Jeong Un",
    account: "kimj",
    blueCheck: false,
    followers: "1.1k",
  ),
  SearchData(
    avatar: "assets/avatars/psw.jpg",
    name: "Park Seong Woong",
    account: "gooddaytodie",
    blueCheck: true,
    followers: "3.1k",
  ),
  SearchData(
    avatar: "assets/avatars/tony.jpeg",
    name: "Tony Stark",
    account: "iamironman",
    blueCheck: true,
    followers: "45.5M",
  ),
  SearchData(
    avatar: "assets/avatars/trump.jpeg",
    name: "Donald Trump",
    account: "america1st",
    blueCheck: true,
    followers: "4.5M",
  ),
  SearchData(
    avatar: "assets/avatars/ma.jpeg",
    name: "Don Lee",
    account: "donlee",
    blueCheck: true,
    followers: "1.5M",
  ),
  SearchData(
    avatar: "assets/avatars/zcbg.jpeg",
    name: "Mark Zuckerberg",
    account: "meta",
    blueCheck: true,
    followers: "23.1M",
  ),
];

final fakeDataActivity = [
  ActivityData(
      avatar: "assets/avatars/zcbg.jpeg",
      account: "meta",
      time: "4h",
      category: "Mentioned you",
      avatarCategory: "Mentions",
      text: "Here's a thread you should follow if you love meta @meta",
      following: false),
  ActivityData(
      avatar: "assets/avatars/nike.png",
      account: "nike",
      time: "6h",
      category: "Starting out my sports club with threads, follow me!",
      avatarCategory: "Replies",
      text: "Count me in!",
      following: false),
  ActivityData(
      avatar: "assets/avatars/mnk.jpg",
      account: "brighteyes",
      time: "7h",
      category: "Followed you",
      avatarCategory: "Following",
      following: true),
  ActivityData(
      avatar: "assets/avatars/fu.jpg",
      account: "fubao",
      time: "8h",
      category: "Eat bamboo! 🐼🐼🐼🌴",
      avatarCategory: "Likes",
      following: false),
  ActivityData(
      avatar: "assets/avatars/ma.jpeg",
      account: "donlee",
      time: "8h",
      category: "😗 😙 😚",
      avatarCategory: "Likes",
      following: false),
];
